//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace another_pet_shop.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class items
    {
        public int id { get; set; }
        public string article { get; set; }
        public int idName { get; set; }
        public int idQuantityType { get; set; }
        public int cost { get; set; }
        public int maxDiscount { get; set; }
        public int idProducer { get; set; }
        public int idDeliverer { get; set; }
        public int irCategory { get; set; }
        public int currentDiscount { get; set; }
        public int inStock { get; set; }
        public string description { get; set; }
        public string image { get; set; }
        public string imageHolder { get; set; }
    
        public virtual category category { get; set; }
        public virtual deliverer deliverer { get; set; }
        public virtual name name { get; set; }
        public virtual producer producer { get; set; }
        public virtual quantityType quantityType { get; set; }
    }
}
