//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace another_pet_shop.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders
    {
        public int id { get; set; }
        public string structure { get; set; }
        public System.DateTime orderDate { get; set; }
        public System.DateTime deliverDate { get; set; }
        public int point { get; set; }
        public string lname { get; set; }
        public string fname { get; set; }
        public string patro { get; set; }
        public int code { get; set; }
        public int idStatus { get; set; }
    
        public virtual points points { get; set; }
        public virtual status status { get; set; }
    }
}
