//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace another_pet_shop.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int id { get; set; }
        public int idRoles { get; set; }
        public string lname { get; set; }
        public string fname { get; set; }
        public string patro { get; set; }
        public string login { get; set; }
        public string password { get; set; }
    
        public virtual roles roles { get; set; }
    }
}
